# Generated by Django 4.0.5 on 2022-08-04 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='account',
            new_name='currency',
        ),
    ]
