# Generated by Django 4.0.5 on 2022-08-11 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currencyapp', '0002_rename_account_customer_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='currency_word',
        ),
    ]
