# Generated by Django 4.0.5 on 2022-08-29 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company',
            new_name='album_company',
        ),
    ]
