# Generated by Django 4.0.5 on 2022-07-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binaryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='dt',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
