# Generated by Django 4.0.5 on 2022-08-26 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmiapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bmimodel',
            old_name='bmi_value',
            new_name='calculatedbmi',
        ),
    ]
