# Generated by Django 4.0.5 on 2022-08-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filepath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('newimage', models.ImageField(upload_to='')),
                ('dt', models.DateTimeField()),
            ],
        ),
    ]
