# Generated by Django 4.0.5 on 2022-08-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filepathapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filepath',
            name='dt',
        ),
        migrations.AddField(
            model_name='filepath',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
