# Generated by Django 4.0.5 on 2022-08-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRcodeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_address', models.CharField(max_length=100)),
                ('item_code', models.BinaryField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='generator',
        ),
    ]
