# Generated by Django 4.0.5 on 2022-07-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('roll_no', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
