# Generated by Django 4.0.5 on 2022-08-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgetpasswordapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='resetmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('new_password', models.CharField(max_length=25)),
                ('re_type_password', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='forgetmodel',
        ),
    ]
