# Generated by Django 4.0.5 on 2022-08-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forgetpasswordapp', '0002_resetmodel_delete_forgetmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='forgetmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('new_password', models.CharField(max_length=25)),
                ('confirm_password', models.CharField(max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='resetmodel',
        ),
    ]
