# Generated by Django 4.0.5 on 2022-08-29 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forgetpasswordapp', '0003_forgetmodel_delete_resetmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgetmodel',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='forgetmodel',
            name='new_password',
        ),
    ]
