# Generated by Django 4.0.5 on 2022-08-09 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculateageapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dobtoage',
            old_name='date',
            new_name='dob',
        ),
    ]
