# Generated by Django 4.0.5 on 2022-08-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='folderapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=100)),
                ('book_address', models.CharField(max_length=100)),
                ('book_field', models.CharField(max_length=80)),
                ('book_code', models.BinaryField(max_length=150)),
            ],
        ),
    ]
